defmodule MydiaWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :mydia

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_mydia_key",
    signing_salt: "aGjwFmlL",
    same_site: "Lax",
    # 30 days in seconds - matches Guardian JWT TTL
    max_age: 30 * 24 * 60 * 60
  ]

  # Enable SQL sandbox for browser-based feature tests (Wallaby)
  # This allows browser requests to participate in the test transaction
  # The plug only activates when sandbox metadata is present in the request
  plug Phoenix.Ecto.SQL.Sandbox

  # Trust X-Forwarded-* headers from reverse proxy (Caddy)
  # This ensures conn.scheme reflects the original HTTPS request
  # Required for OIDC redirect URI validation when behind a proxy
  plug Plug.RewriteOn, [:x_forwarded_host, :x_forwarded_port, :x_forwarded_proto]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # WebSocket for device reconnection
  socket "/ws", MydiaWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :mydia,
    gzip: not code_reloading?,
    only: MydiaWeb.static_paths()

  # Serve generated media content (thumbnails, sprites, previews)
  # Files are stored in a configurable directory with content-addressable naming
  # Use Application.compile_env for compile-time configuration or fallback to default
  plug Plug.Static,
    at: "/generated",
    from:
      Application.compile_env(:mydia, :generated_media_path) ||
        Path.join(Application.app_dir(:mydia, "priv"), "generated"),
    gzip: false,
    cache_control_for_etags: "public, max-age=31536000",
    headers: %{"access-control-allow-origin" => "*"}

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :mydia
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  plug MydiaWeb.Router
end
